apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: infradeploy
  name: deployment-manager
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "create", "update", "delete"]

